# Generated by Django 4.2.7 on 2023-11-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nomeDoAutor', models.CharField(max_length=200)),
                ('anoDeLançamento', models.IntegerField()),
                ('numEdicao', models.IntegerField()),
            ],
        ),
    ]
