# Generated by Django 4.2.7 on 2023-11-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='anoDeLançamento',
            new_name='lancamento',
        ),
        migrations.AddField(
            model_name='livro',
            name='anoEdicao',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='tipo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
